_BASE_: "../Base-RCNN-DilatedC5.yaml"
MODEL:
  META_ARCHITECTURE: "DAWSOD_RCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
    OUT_FEATURES: ["res2", "res5"]
  BACKBONE:
    FREEZE_AT: 0
    NAME: build_resnet_backbone
  PROPOSAL_GENERATOR:
    NAME: "DAWSOD_RPN"
  ROI_HEADS:
    NAME: "DAWSOD_ROIHeads"
    NUM_CLASSES: 20
  ROI_BOX_HEAD:
    NAME: "DAWSOD_FastRCNNConvFCHead"
  RETINANET:
    NUM_CLASSES: 20
    NORM: "SyncBN"
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
TEST:
  EVAL_PERIOD: 2000
DATASETS:
  TRAIN: ('clipart1k_train',)
  TRAIN_SOURCE: ('voc_2007_trainval', 'voc_2012_trainval')
  TEST: ('clipart1k_test',)
SOLVER:
  CHECKPOINT_PERIOD: 2000
  STEPS: (24000, 32000)
  MAX_ITER: 72000
  WARMUP_ITERS: 400
  IMS_PER_BATCH: 4 # image number for each domain
  BASE_LR: 0.005 
OUTPUT_DIR: "./output"
DATALOADER:
  NUM_WORKERS: 4
